---
title: "Freedman example"
author: "Put your name here"
date: "2025-01-30"
output: html_document
---

# Utility function (to generate data)

Function adapted from Layla's code for simulation data generation.

```{r}
########################################
### Functions to generate data ######
########################################

gen.data = function(setting, n1, n0) {
	if(setting == 1)
	{	s1 = g.1(n1)
		y1 = f.cond.1(s1)
		s0 = g.0(n0)
		y0 = f.cond.0(s0)
		return(data.frame("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}
	if(setting == 2)
	{
	s1 = g.1.exp(n1)
	y1 = f.cond.1.exp(s1)
	s0 = g.0.exp(n0)
	y0 = f.cond.0.exp(s0)
	return(data.frame("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}
	if(setting==3)
	{
	s1 = g.1(n1, alpha0=-0.33333333333)
	y1 = f.cond.1(s1)
	s0 = g.0(n0, alpha0=-0.33333333333)
	y0 = f.cond.0(s0)
	return(list("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}

}
	
f.cond.1 = function(s.vector) {
	eps1 = rnorm(length(s.vector),0,3)
	y1 = 2+5*s.vector+1 + 1*s.vector + eps1
	return(y1)		
}

f.cond.0 = function(s.vector) {
	eps0 = rnorm(length(s.vector),0,3)
	y0 = 2+5*s.vector+ eps0
	return(y0)		
}

f.cond.0.exp = function(s.vector ) {
	y = 0.8*s.vector^2 + .2*exp(s.vector/5) + exp(rnorm(length(s.vector),0 ,.3))
	return(y)
}

f.cond.1.exp = function(s.vector) {
	 y = .5+s.vector^2 + .5*exp(s.vector/5) + exp(rnorm(length(s.vector),0, .3))
	return(y)		
}

g.1 = function(n, alpha0=5) { return(rnorm(n, alpha0 + 1,2))}
g.0 = function(n,alpha0=5) { return(rnorm(n, alpha0,1))}
g.1.exp = function(n) { return(exp(rnorm(n,1.7, .2)))}
g.0.exp = function(n) { return(exp(rnorm(n,1.62, .1)))}

########################################
### Function to generate the truth ####
########################################
#this function will get more complicated when the parametric models don't hold

get.true = function(setting) {
	if(setting == 1)
	{return(list("delta.s.true" = 6, "delta.true" = 12, "R.true" = 0.5))}	

	if(setting == 2)
	{data = gen.data(setting=2, n1=100000, n0=100000) 
	s1 = data$s1
	y1 = data$y1
	s0 = data$s0
	y0 = data$y0
	delta.true = mean(y1)-mean(y0)
	y1.ifs0 = f.cond.1.exp(s0)
	delta.s.true = mean(y1.ifs0) - mean(y0)
	R.true = 1-(delta.s.true/delta.true)
	return(list("delta.s.true" = delta.s.true, "delta.true" = delta.true, "R.true" = R.true))
	}
	
	if(setting == 3)
	{return(list("delta.s.true" = .66666666666666666, "delta.true" = 6.666666666666666, "R.true" = 0.9))}	

}
```



# Library

```{r}
library("Rsurrogate")
```


# Generate data

```{r}
# set seed
sim_seed = 30
# set num of reps
num_reps=1000
# set sample size
n1 = 1000 ### control group size
n0 = 1000 ### treatment group size
# prop of missingness for each treatment group, from 0 to 1
prop_obs_s0 = 0.7
prop_obs_s1 = 0.7

set.seed(sim_seed)

data = gen.data(setting=1, n1=n1, n0=n0) 
```


# One iteration

```{r}
# Define vectors for outcomes/surrogates in untreated/treated 
s1 = data$s1
y1 = data$y1
s0 = data$s0
y0 = data$y0

##########################################################
#Estimates with complete data ############################
##########################################################
## Estimate R with nonparametric approach (robust)
Rnonparam = Rsurrogate::R.s.estimate(sone=s1, 
                                     szero=s0, 
                                     yone = y1, 
                                     yzero = y0, 
                                     type = "robust")
Rnonparam$R.s

## Estimate R with parametric approach (Wang's approach) 
Rwang = Rsurrogate::R.s.estimate(sone=s1, 
                                  szero=s0, 
                                  yone = y1, 
                                  yzero = y0, 
                                  type = "model")
Rwang$R.s

## Estimate R with parametric approach (Freedman's approach) ###
Rfreedman = Rsurrogate::R.s.estimate(sone=s1, 
                                szero=s0, 
                                yone = y1, 
                                yzero = y0, 
                                type = "freedman")
Rfreedman$R.s

##########################################################
#Estimates with incomplete data ##########################
##########################################################

# Simulate non-missingness indicators ###################
## Under MCAR, everybody has 30% missingness probability
m1.1 = rbinom(n1,1,prop_obs_s1) 
m1.0 = rbinom(n0,1,prop_obs_s0)
## Missingness weight
w.y1 = rep(0.7, n1)
w.y0 = rep(0.7, n0)

## Estimate R with nonparametric approach (complete case)
Rnonparam_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                          szero=s0[m1.0==1], 
                                          yone = y1[m1.1==1], 
                                          yzero = y0[m1.0==1], 
                                          type = "robust")
Rnonparam_miss$R.s

 ## Estimate R with nonparametric approach (complete case)
Rwang_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                          szero=s0[m1.0==1], 
                                          yone = y1[m1.1==1], 
                                          yzero = y0[m1.0==1], 
                                          type = "model")
Rwang_miss$R.s

 ## Estimate R with nonparametric approach (complete case)
Rfreedman_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                          szero=s0[m1.0==1], 
                                          yone = y1[m1.1==1], 
                                          yzero = y0[m1.0==1], 
                                          type = "freedman")
Rfreedman_miss$R.s
```



# Simulations with different methods

The robust, Wang, and Freedman approach for non-missing data.

## Sim settings

```{r}
# set seed
sim_seed = 30
# set num of reps
num_reps=1000
# set sample size
n1 = 1000 ### control group size
n0 = 1000 ### treatment group size
# prop of missingness for each treatment group, from 0 to 1
prop_obs_s0 = 0.7
prop_obs_s1 = 0.7

set.seed(sim_seed)

sim_result = data.frame(
      sim = paste(sim_seed, 1:num_reps, sep = "-"),
      n1 = n1, n0 = n0, prop_obs_s0 = prop_obs_s0, prop_obs_s1 = prop_obs_s1,
      Rnonparam = NA, Rwang = NA, Rfreedman = NA,
      Rnonparam_miss = NA, Rwang_miss = NA, Rfreedman_miss = NA
    )
```

## Simulation loop

```{r}
for(iter in 1:num_reps){
  # Generate data 
  data = gen.data(setting=1, n1=n1, n0=n0) 
  
  # Define vectors for outcomes/surrogates in untreated/treated 
  s1 = data$s1
  y1 = data$y1
  s0 = data$s0
  y0 = data$y0
  
  ##########################################################
  #Estimates with complete data ############################
  ##########################################################
  ## Estimate R with nonparametric approach (robust)
  Rnonparam = Rsurrogate::R.s.estimate(sone=s1, 
                                       szero=s0, 
                                       yone = y1, 
                                       yzero = y0, 
                                       type = "robust")
  sim_result$Rnonparam[iter] = Rnonparam$R.s
  
  ## Estimate R with parametric approach (Wang's approach) 
  Rwang = Rsurrogate::R.s.estimate(sone=s1, 
                                    szero=s0, 
                                    yone = y1, 
                                    yzero = y0, 
                                    type = "model")
  sim_result$Rwang[iter] = Rwang$R.s
  
  ## Estimate R with parametric approach (Freedman's approach) ###
  Rfreedman = Rsurrogate::R.s.estimate(sone=s1, 
                                  szero=s0, 
                                  yone = y1, 
                                  yzero = y0, 
                                  type = "freedman")
  sim_result$Rfreedman[iter] = Rfreedman$R.s
  
  ##########################################################
  #Estimates with incomplete data ##########################
  ##########################################################
  
  # Simulate non-missingness indicators ###################
  ## Under MCAR, everybody has 30% missingness probability
  m1.1 = rbinom(n1,1,prop_obs_s1) 
  m1.0 = rbinom(n0,1,prop_obs_s0)
  ## Missingness weight
  w.y1 = rep(0.7, n1)
  w.y0 = rep(0.7, n0)
  
  ## Estimate R with nonparametric approach (complete case)
  Rnonparam_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                            szero=s0[m1.0==1], 
                                            yone = y1[m1.1==1], 
                                            yzero = y0[m1.0==1], 
                                            type = "robust")
  sim_result$Rnonparam_miss[iter] = Rnonparam_miss$R.s
  
   ## Estimate R with nonparametric approach (complete case)
  Rwang_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                            szero=s0[m1.0==1], 
                                            yone = y1[m1.1==1], 
                                            yzero = y0[m1.0==1], 
                                            type = "model")
  sim_result$Rwang_miss[iter] = Rwang_miss$R.s
  
   ## Estimate R with nonparametric approach (complete case)
  Rfreedman_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                            szero=s0[m1.0==1], 
                                            yone = y1[m1.1==1], 
                                            yzero = y0[m1.0==1], 
                                            type = "freedman")
  sim_result$Rfreedman_miss[iter] = Rfreedman_miss$R.s
  
}
```

# Graphical summary of simulation results

```{r}
boxplot(sim_result[,6:11])
abline(h = 0.5, col = "red", lwd = 2, lty = 2)
```