---
title: "Freedman example"
author: "Put your name here"
date: "2025-01-30"
output: html_document
---

# Utility function (to generate data)

Function adapted from Layla's code for simulation data generation.

```{r}
########################################
### Functions to generate data ######
########################################

gen.data = function(setting, n1, n0) {
	if(setting == 1)
	{	s1 = g.1(n1)
		y1 = f.cond.1(s1)
		s0 = g.0(n0)
		y0 = f.cond.0(s0)
		return(data.frame("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}
	if(setting == 2)
	{
	s1 = g.1.exp(n1)
	y1 = f.cond.1.exp(s1)
	s0 = g.0.exp(n0)
	y0 = f.cond.0.exp(s0)
	return(data.frame("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}
	if(setting==3)
	{
	s1 = g.1(n1, alpha0=-0.33333333333)
	y1 = f.cond.1(s1)
	s0 = g.0(n0, alpha0=-0.33333333333)
	y0 = f.cond.0(s0)
	return(list("s1" = s1, "y1" = y1, "s0" = s0, "y0" = y0))
	}

}
	
f.cond.1 = function(s.vector) {
	eps1 = rnorm(length(s.vector),0,3)
	y1 = 2+5*s.vector+1 + 1*s.vector + eps1
	return(y1)		
}

f.cond.0 = function(s.vector) {
	eps0 = rnorm(length(s.vector),0,3)
	y0 = 2+5*s.vector+ eps0
	return(y0)		
}

f.cond.0.exp = function(s.vector ) {
	y = 0.8*s.vector^2 + .2*exp(s.vector/5) + exp(rnorm(length(s.vector),0 ,.3))
	return(y)
}

f.cond.1.exp = function(s.vector) {
	 y = .5+s.vector^2 + .5*exp(s.vector/5) + exp(rnorm(length(s.vector),0, .3))
	return(y)		
}

g.1 = function(n, alpha0=5) { return(rnorm(n, alpha0 + 1,2))}
g.0 = function(n,alpha0=5) { return(rnorm(n, alpha0,1))}
g.1.exp = function(n) { return(exp(rnorm(n,1.7, .2)))}
g.0.exp = function(n) { return(exp(rnorm(n,1.62, .1)))}

########################################
### Function to generate the truth ####
########################################
#this function will get more complicated when the parametric models don't hold

get.true = function(setting) {
	if(setting == 1)
	{return(list("delta.s.true" = 6, "delta.true" = 12, "R.true" = 0.5))}	

	if(setting == 2)
	{data = gen.data(setting=2, n1=100000, n0=100000) 
	s1 = data$s1
	y1 = data$y1
	s0 = data$s0
	y0 = data$y0
	delta.true = mean(y1)-mean(y0)
	y1.ifs0 = f.cond.1.exp(s0)
	delta.s.true = mean(y1.ifs0) - mean(y0)
	R.true = 1-(delta.s.true/delta.true)
	return(list("delta.s.true" = delta.s.true, "delta.true" = delta.true, "R.true" = R.true))
	}
	
	if(setting == 3)
	{return(list("delta.s.true" = .66666666666666666, "delta.true" = 6.666666666666666, "R.true" = 0.9))}	

}
```



# Library

```{r}
library("Rsurrogate")
```


# Generate data

```{r}
# set seed
sim_seed = 30
# set num of reps
num_reps=1000
# set sample size
n1 = 1000 ### control group size
n0 = 1000 ### treatment group size
# prop of missingness for each treatment group, from 0 to 1
prop_obs_s0 = 0.7
prop_obs_s1 = 0.7

set.seed(sim_seed)

data = gen.data(setting=1, n1=n1, n0=n0) 
```


# One iteration

```{r}
# Define vectors for outcomes/surrogates in untreated/treated 
s1 = data$s1
y1 = data$y1
s0 = data$s0
y0 = data$y0

### Reformat data into dataframe

df = data.frame(
  Y = c(y0, y1),
  S = c(s0,s1),
  Z = rep(c(0,1), times = c(n0, n1)),
  Smiss = c(s0,s1)
)

##########################################################
#Estimates with complete data ############################
##########################################################
## Estimate R with nonparametric approach (robust)
#Rnonparam = Rsurrogate::R.s.estimate(sone=s1, 
#                                     szero=s0, 
#                                     yone = y1, 
#                                     yzero = y0, 
#                                     type = "robust")
#Rnonparam$R.s

## Estimate R with parametric approach (Wang's approach) 
R_gold = Rsurrogate::R.s.estimate(sone=s1, 
                                  szero=s0, 
                                  yone = y1, 
                                  yzero = y0, 
                                  type = "model")
R_gold$R.s

### from scratch
fit = lm(Y~Z*S, data = df)
summary(fit)
gamma0 = fit$coefficients[1]
gamma1 = fit$coefficients[3]
gamma2 = gamma0 + fit$coefficients[2]
gamma3 = gamma1 + fit$coefficients[4]

alpha0 = mean(s0) ## Sample mean of S among Z = 0
alpha1 = mean(s1) ## Sample mean of S among Z = 1

delta = (gamma2 - gamma0) + gamma1 * (alpha1 - alpha0) + (gamma3 - gamma1) * alpha1 
deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0
R = 1 - deltaS / delta 

## Estimate R with parametric approach (Freedman's approach) ###
#Rfreedman = Rsurrogate::R.s.estimate(sone=s1, 
#                                szero=s0, 
#                                yone = y1, 
#                                yzero = y0, 
#                                type = "freedman")
#Rfreedman$R.s

##########################################################
#Estimates with incomplete data ##########################
##########################################################


# Simulate non-missingness indicators ###################
## Under MCAR, everybody has 30% missingness probability
m1.1 = rbinom(n1,1,prop_obs_s1) 
m1.0 = rbinom(n0,1,prop_obs_s0)
## Missingness weight
w.y1 = rep(0.7, n1)
w.y0 = rep(0.7, n0)
## make data missing
df$Smiss[c(m1.0, m1.1) == 0] = NA
df$weights = c(w.y0,w.y1)

## Complete case analysis

### Estimate R with nonparametric approach (complete case)
#Rnonparam_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
#                                          szero=s0[m1.0==1], 
#                                          yone = y1[m1.1==1], 
#                                          yzero = y0[m1.0==1], 
#                                          type = "robust")
#Rnonparam_miss$R.s

 ### Estimate R with nonparametric approach (complete case)
R_miss_complete = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                          szero=s0[m1.0==1], 
                                          yone = y1[m1.1==1], 
                                          yzero = y0[m1.0==1], 
                                          type = "model")
R_miss_complete$R.s

### Estimate R with nonparametric approach (complete case)
#Rfreedman_miss = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
#                                          szero=s0[m1.0==1], 
#                                          yone = y1[m1.1==1], 
#                                          yzero = y0[m1.0==1], 
#                                          type = "freedman")
#Rfreedman_miss$R.s




## IPW

### Estimate R with IPW only (robust)


### Estimate R with IPW only (semiparam)

#### Fit Y ~ Z + S
lm_ipw_semiparam = lm(formula = Y ~ Z*Smiss, 
                      data = df, 
                      weights = weights)
summary(lm_ipw_semiparam)

##### Get coefficients
gamma0 = as.numeric(lm_ipw_semiparam$coefficients[1])
gamma1 = as.numeric(lm_ipw_semiparam$coefficients[3])
gamma2 = gamma0 + as.numeric(lm_ipw_semiparam$coefficients[2])
gamma3 = gamma1 + as.numeric(lm_ipw_semiparam$coefficients[4])

#### Fit S ~ Z with IPW
lm_surr_weighted = lm(formula = Smiss ~ Z, data = df, 
             weights = weights)
summary(lm_surr_weighted)
##### Get coefficients
alpha0_weighted = as.numeric(lm_surr_weighted$coefficients[1])
alpha1_weighted = alpha0_weighted + as.numeric(lm_surr_weighted$coefficients[2])

#### Calculate PTE 
delta = (gamma2 - gamma0) + gamma1 * (alpha1_weighted - alpha0_weighted) + (gamma3 - gamma1) * alpha1_weighted
deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_weighted
R = 1 - deltaS / delta 

#### Fit S ~ Z complete case
lm_surr_comp = lm(formula = Smiss ~ Z, data = df)
##### Get coefficients
alpha0_comp = as.numeric(coefficients(lm_surr_comp)[1])
alpha1_comp = alpha0_comp + as.numeric(coefficients(lm_surr_comp)[2])

#### Calculate PTE 
delta = (gamma2 - gamma0) + gamma1 * (alpha1_comp - alpha0_comp) + (gamma3 - gamma1) * alpha1_comp 
deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_comp
R = 1 - deltaS / delta 

## smle

### Estimate R with smle & IPW (semiparam)

##### creating treatment group indicator
df$bs1 = as.numeric(df$Z == 0) ## Create bs1 = I(Z = 0), treated 
df$bs2 = as.numeric(df$Z == 1) ## Create bs2 = I(Z = 1), untreated

##### creating covariates for interaction model
df$Sinter = df$Smiss*df$Z

#### fit Y ~ Z*S with smle
fit = TwoPhaseReg::smle(Y = "Y", ## outcome  
                      X = c("Smiss", "Sinter"), ## "expensive" covariate (with missing data)
                      Z = "Z", ## "inexpensive" covariate (without missing data)
                      Bspline_Z = c("bs1", "bs2"), ## B-splines / indicators for Z 
                      data = df, ## name of the dataset 
                      noSE = FALSE, ## do you want standard error estimates? 
                      TOL = 1E-4, ## used to define convergence
                      MAX_ITER = 500, ## used to keep it from blowing up 
                      model = "linear" ## type of outcome model - we want OLS
)
##### Get coefficients
fit$coefficients
gamma0 = as.numeric(fit$coefficients[1])
gamma1 = as.numeric(fit$coefficients[2])
gamma2 = gamma0 + as.numeric(fit$coefficients[4])
gamma3 = gamma1 + as.numeric(fit$coefficients[3])

#### Calculate PTE 
delta = (gamma2 - gamma0) + gamma1 * (alpha1_weighted - alpha0_weighted) + (gamma3 - gamma1) * alpha1_weighted
deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_weighted
R = 1 - deltaS / delta 


#### Calculate PTE 
delta = (gamma2 - gamma0) + gamma1 * (alpha1_comp - alpha0_comp) + (gamma3 - gamma1) * alpha1_comp 
deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_comp
R = 1 - deltaS / delta 


```



# Simulations with different methods


## Sim settings

```{r}
# set seed
sim_seed = 311611
# set num of reps
num_reps=500
# set sample size
n1 = 1000 ### control group size
n0 = 1000 ### treatment group size
# prop of missingness for each treatment group, from 0 to 1
prop_obs_s0 = 0.7
prop_obs_s1 = 0.7

set.seed(sim_seed)

sim_result = data.frame(
      sim = paste(sim_seed, 1:num_reps, sep = "-"),
      n1 = n1, n0 = n0, prop_obs_s0 = prop_obs_s0, prop_obs_s1 = prop_obs_s1,
      R.gold = NA, R.complete = NA, R.ipw.ipw = NA, R.ipw.complete = NA,
      R.smle.ipw = NA, R.smle.complete = NA
    )
```

## Simulation loop

```{r}
for(iter in 1:num_reps){
  # Generate data 
  data = gen.data(setting=1, n1=n1, n0=n0) 
  # Define vectors for outcomes/surrogates in untreated/treated 
  s1 = data$s1
  y1 = data$y1
  s0 = data$s0
  y0 = data$y0
  
  ### Reformat data into dataframe
  
  df = data.frame(
    Y = c(y0, y1),
    S = c(s0,s1),
    Z = rep(c(0,1), times = c(n0, n1)),
    Smiss = c(s0,s1)
  )
  
  ##########################################################
  #Estimates with complete data ############################
  ##########################################################
  
  ## Estimate R with parametric approach (Wang's approach) 
  R_gold = Rsurrogate::R.s.estimate(sone=s1, 
                                    szero=s0, 
                                    yone = y1, 
                                    yzero = y0, 
                                    type = "model")
  sim_result$R.gold[iter] = R_gold$R.s
  
  ##########################################################
  #Estimates with incomplete data ##########################
  ##########################################################
  
  
  # Simulate non-missingness indicators ###################
  ## Under MCAR, everybody has 30% missingness probability
  m1.1 = rbinom(n1,1,prop_obs_s1) 
  m1.0 = rbinom(n0,1,prop_obs_s0)
  df$Smiss[c(m1.0, m1.1) == 0] = NA
  ## Missingness weight
  w.y1 = rep(0.7, n1)
  w.y0 = rep(0.7, n0)
  df$weights = c(w.y0,w.y1)
  
   ### Estimate R with nonparametric approach (complete case)
  R_miss_complete = Rsurrogate::R.s.estimate(sone=s1[m1.1==1], 
                                            szero=s0[m1.0==1], 
                                            yone = y1[m1.1==1], 
                                            yzero = y0[m1.0==1], 
                                            type = "model")
  sim_result$R.complete[iter] = R_miss_complete$R.s
  
  ## IPW
  
  ### Estimate R with IPW only (semiparam)
  
  #### Fit Y ~ Z + S
  lm_ipw_semiparam = lm(formula = Y ~ Z*Smiss, 
                        data = df, 
                        weights = weights)
  summary(lm_ipw_semiparam)
  
  ##### Get coefficients
  gamma0 = as.numeric(lm_ipw_semiparam$coefficients[1])
  gamma1 = as.numeric(lm_ipw_semiparam$coefficients[3])
  gamma2 = gamma0 + as.numeric(lm_ipw_semiparam$coefficients[2])
  gamma3 = gamma1 + as.numeric(lm_ipw_semiparam$coefficients[4])
  
  #### Fit S ~ Z with IPW
  lm_surr_weighted = lm(formula = Smiss ~ Z, data = df, 
               weights = weights)
  summary(lm_surr_weighted)
  ##### Get coefficients
  alpha0_weighted = as.numeric(lm_surr_weighted$coefficients[1])
  alpha1_weighted = alpha0_weighted + as.numeric(lm_surr_weighted$coefficients[2])
  
  #### Calculate PTE 
  delta = (gamma2 - gamma0) + gamma1 * (alpha1_weighted - alpha0_weighted) + (gamma3 - gamma1) * alpha1_weighted
  deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_weighted
  sim_result$R.ipw.ipw[iter]  = 1 - deltaS / delta 
  
  #### Fit S ~ Z complete case
  lm_surr_comp = lm(formula = Smiss ~ Z, data = df)
  ##### Get coefficients
  alpha0_comp = as.numeric(coefficients(lm_surr_comp)[1])
  alpha1_comp = alpha0_comp + as.numeric(coefficients(lm_surr_comp)[2])
  
  #### Calculate PTE 
  delta = (gamma2 - gamma0) + gamma1 * (alpha1_comp - alpha0_comp) + (gamma3 - gamma1) * alpha1_comp 
  deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_comp
  sim_result$R.ipw.complete[iter]  = 1 - deltaS / delta 
  
  ## smle
  
  ### Estimate R with smle & IPW (semiparam)
  
  ##### creating treatment group indicator
  df$bs1 = as.numeric(df$Z == 0) ## Create bs1 = I(Z = 0), treated 
  df$bs2 = as.numeric(df$Z == 1) ## Create bs2 = I(Z = 1), untreated
  
  ##### creating covariates for interaction model
  df$Sinter = df$Smiss*df$Z
  
  #### fit Y ~ Z*S with smle
  fit = TwoPhaseReg::smle(Y = "Y", ## outcome  
                        X = c("Smiss", "Sinter"), ## "expensive" covariate (with missing data)
                        Z = "Z", ## "inexpensive" covariate (without missing data)
                        Bspline_Z = c("bs1", "bs2"), ## B-splines / indicators for Z 
                        data = df, ## name of the dataset 
                        noSE = FALSE, ## do you want standard error estimates? 
                        TOL = 1E-4, ## used to define convergence
                        MAX_ITER = 500, ## used to keep it from blowing up 
                        model = "linear" ## type of outcome model - we want OLS
  )
  ##### Get coefficients
  fit$coefficients
  gamma0 = as.numeric(fit$coefficients[1])
  gamma1 = as.numeric(fit$coefficients[2])
  gamma2 = gamma0 + as.numeric(fit$coefficients[4])
  gamma3 = gamma1 + as.numeric(fit$coefficients[3])
  
  #### Calculate PTE 
  delta = (gamma2 - gamma0) + gamma1 * (alpha1_weighted - alpha0_weighted) + (gamma3 - gamma1) * alpha1_weighted
  deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_weighted
  sim_result$R.smle.ipw[iter]  = 1 - deltaS / delta  
  
  
  #### Calculate PTE 
  delta = (gamma2 - gamma0) + gamma1 * (alpha1_comp - alpha0_comp) + (gamma3 - gamma1) * alpha1_comp 
  deltaS = (gamma2 - gamma0) + (gamma3 - gamma1) * alpha0_comp
  sim_result$R.smle.complete[iter]  = 1 - deltaS / delta 
    
    
}
```

# Graphical summary of simulation results

```{r}
boxplot(sim_result[,6:11])
abline(h = 0.5, col = "red", lwd = 2, lty = 2)
```